# Generated by Django 5.0.6 on 2026-09-19 02:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0004_professionalservice_observations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('category', models.CharField(default='error_mapa', max_length=50)),
                ('category_label', models.CharField(default='Falla en Mapa / GPS Bogotá', max_length=100)),
                ('description', models.TextField()),
                ('device_info', models.CharField(blank=True, default='Android / Web', max_length=150)),
                ('reported_by', models.CharField(default='Laura Gómez', max_length=150)),
                ('status', models.CharField(choices=[('recibido', 'Recibido / En Análisis'), ('en_proceso', 'En Corrección Técnica'), ('resuelto', 'Corregido en Producción')], default='recibido', max_length=30)),
                ('response_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problema Técnico de la App',
                'verbose_name_plural': 'Problemas Técnicos de la App',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PQRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('client_name', models.CharField(default='Laura Gómez', max_length=150)),
                ('client_phone', models.CharField(default='+57 310 445 8892', max_length=50)),
                ('client_email', models.EmailField(default='laura.gomez@bogota.co', max_length=254)),
                ('client_document_id', models.CharField(default='CC 52.894.120', max_length=50)),
                ('client_address', models.CharField(default='Cra. 11 # 85-32, Chicó, Bogotá', max_length=255)),
                ('contractor_id_ref', models.CharField(db_index=True, default='carlos-mendoza', max_length=100)),
                ('contractor_name', models.CharField(default='Ing. Carlos Mendoza', max_length=150)),
                ('contractor_company', models.CharField(default='Mendoza Instalaciones Eléctricas RETIE', max_length=150)),
                ('contractor_specialty', models.CharField(blank=True, default='Electricidad y Certificación RETIE', max_length=150)),
                ('contractor_avatar', models.TextField(blank=True, default='')),
                ('pqr_type', models.CharField(choices=[('queja', 'Queja de Trato/Servicio'), ('reclamo', 'Reclamo Técnico de Obra'), ('recurso_garantia', 'Recurso de Garantía 6 Meses'), ('peticion', 'Petición Formal')], default='queja', max_length=30)),
                ('reason', models.CharField(default='mala_calidad_obra', max_length=60)),
                ('status', models.CharField(choices=[('radicado', 'Radicado / En espera'), ('en_revision', 'En Revisión Técnica / Jurídica'), ('conciliacion', 'En Mesa de Conciliación'), ('resuelto', 'Resuelto a Satisfacción'), ('sancionado', 'Contratista Sancionado')], db_index=True, default='radicado', max_length=30)),
                ('incident_date', models.DateField(default=datetime.date.today)),
                ('amount_disputed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('desired_resolution', models.TextField(default='Revisión técnica urgente, garantía vinculante y mediación formal por la Defensoría de Bogotá.')),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('admin_resolution_notes', models.TextField(blank=True, default='')),
                ('estimated_response_days', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqr_reports', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqr_complaints', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'PQR / Reclamo',
                'verbose_name_plural': 'PQRS / Reclamos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PQRMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('client', 'Cliente'), ('contractor', 'Contratista'), ('support_agent', 'Agente Soporte'), ('system', 'Sistema')], default='client', max_length=30)),
                ('sender_name', models.CharField(default='Laura Gómez', max_length=150)),
                ('sender_role', models.CharField(blank=True, default='Cliente', max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pqrs.pqrreport')),
            ],
            options={
                'verbose_name': 'Mensaje PQR',
                'verbose_name_plural': 'Mensajes PQR',
                'ordering': ['timestamp'],
            },
        ),
    ]
