# Generated by Django 5.0.6 on 2026-09-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_alter_pqrreport_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproblemreport',
            name='reported_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pqrmessage',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
