# Generated by Django 5.0.6 on 2026-09-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_alter_appproblemreport_reported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproblemreport',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
