# Generated by Django 5.0.6 on 2026-09-06 18:33

import apps.service_requests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_direct_service_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.service_requests.models.service_request_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service_requests.servicerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagen de solicitud',
                'verbose_name_plural': 'imagenes de solicitud',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
