# Generated by Django 5.0.6 on 2026-09-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('scheduled', 'Agendada'), ('traveling', 'En camino'), ('arrived', 'En el lugar'), ('in_progress', 'En ejecucion'), ('break', 'Descanso'), ('lunch', 'Almuerzo'), ('other_service', 'Otro servicio'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('scheduled', 'Agendada'), ('traveling', 'En camino'), ('arrived', 'En el lugar'), ('in_progress', 'En ejecucion'), ('break', 'Descanso'), ('lunch', 'Almuerzo'), ('other_service', 'Otro servicio'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=20),
        ),
    ]
