# Generated by Django 5.0.6 on 2026-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='Cra. 11 # 85-32, Chicó, Bogotá', max_length=255, verbose_name='direccion principal'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(blank=True, default='CC 52.894.120', max_length=50, verbose_name='documento de identidad'),
        ),
    ]
