# Generated by Django 5.0.6 on 2026-09-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='direccion principal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='documento de identidad'),
        ),
    ]
