# Generated by Django 5.0.6 on 2026-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_address_alter_user_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='url de avatar'),
        ),
    ]
