# Generated by Django 5.0.6 on 2026-09-24 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='ProfessionalUser',
            fields=[
            ],
            options={
                'verbose_name': 'profesional (cuenta)',
                'verbose_name_plural': 'profesionales (cuentas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=120, verbose_name='contacto de emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telefono de emergencia')),
                ('preferred_payment_method', models.CharField(blank=True, default='cash', max_length=50, verbose_name='metodo de pago preferido')),
                ('service_notes', models.TextField(blank=True, default='', verbose_name='preferencias o notas de servicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de cliente',
                'verbose_name_plural': 'perfiles de clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
