# Generated by Django 5.0.6 on 2026-10-09 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clientuser_professionaluser_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='Superadministrador', max_length=150, verbose_name='nombre del administrador')),
                ('action', models.CharField(max_length=150, verbose_name='acción realizada')),
                ('target', models.CharField(max_length=255, verbose_name='elemento o usuario afectado')),
                ('reason', models.TextField(blank=True, default='', verbose_name='motivo o justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
