# Generated by Django 5.0.6 on 2026-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitud'),
        ),
    ]
