# Generated by Django 5.0.6 on 2026-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professionalservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='observations',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
    ]
