# Generated by Django 5.0.6 on 2026-09-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalservice_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialty_label',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='especialidad principal'),
        ),
    ]
