# Generated by Django 5.0.6 on 2026-10-09 00:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_professionalprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='points',
            field=models.PositiveIntegerField(default=1000, verbose_name='puntos de incentivos'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo recarga'),
        ),
    ]
